@startuml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml

@startuml
class ActiveMethodExample
class ActiveMethod

ActiveMethod <-- ActiveMethodExample

ActiveResult <-- ActiveMethod
ActiveRunnable <-- ActiveMethod
ActiveStarter <-- ActiveMethod

ThreadPool <-- ActiveStarter

ActiveRunnableBase <-- ThreadPool
ActiveRunnable <-- ActiveRunnableBase
ActiveResult <-- ActiveRunnable
@enduml
